In [1]:
import urllib.request, urllib.parse, urllib.error
import pandas as pd
pd.options.display.max_columns=50
import numpy as np
import matplotlib.pyplot as plt
import locale
import os
import matplotlib.patches as mpatches
yea=2020
man=1
day=1
ma=9
start_val='{}-{}-{}'.format(yea,man,day)
import sys

from numpy.random import seed
seed(888)
import datetime
today = datetime.date.today() + datetime.timedelta(days=1) # +1 day
dataT=str(today)
os.environ["TF_FORCE_GPU_ALLOW_GROWTH"] = "true"

pathP='/mnt/Production/СМП'

In [2]:
dataT

'2021-09-21'

In [3]:
def cz1(df):
    hours = {}
    hours[1] = [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
    hours[2] = [8, 9, 10, 11, 12, 13, 17, 18, 19, 20, 21]
    hours[3] = [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
    hours[4] = [8, 9, 10, 11, 12, 13, 14, 15, 18, 19, 20, 21]
    hours[5] = [8, 9, 10, 11, 12, 13, 14, 15, 20, 21]
    hours[6] = [8, 9, 10, 11, 12, 13, 14, 15, 16, 20, 21]
    hours[7] = [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 20, 21]
    hours[8] = [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
    hours[9] = [8, 9, 10, 11, 12, 13, 14, 15, 18, 19, 20, 21]
    hours[10] = [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
    hours[11] = [8, 9, 10, 11, 16, 17, 18, 19, 20, 21]
    hours[12] = [8, 9, 10, 11, 12, 15, 16, 17, 18, 19, 20, 21]
    
    df_cat = pd.DataFrame(columns=df.columns, index=df.index)
    i = 0
    for values in df.values:
        cat_arr = []
        for value in values:
            if int(value) in hours[df.index[i].month]:
                cat_arr.append(int(value))
        if len(cat_arr) > 0:
            df_cat['V1'].loc[df.index[i]] = cat_arr[0]
        if len(cat_arr) > 1:
            df_cat['V2'].loc[df.index[i]] = cat_arr[1]
        if len(cat_arr) > 2:
            df_cat['V3'].loc[df.index[i]] = cat_arr[2]
        if len(cat_arr) > 3:
            df_cat['V4'].loc[df.index[i]] = cat_arr[3]
        if len(cat_arr) > 4:
            df_cat['V5'].loc[df.index[i]] = cat_arr[4]
        i += 1
    
    
    return df_cat

def cz2(df):
    hours = {}
    hours[1] = [5, 6, 7, 8, 11, 12, 13, 14, 15, 16, 17]
    hours[2] = [5, 6, 7, 8, 12, 13, 14, 15, 16, 17]
    hours[3] = [5, 6, 7, 8, 13, 14, 15, 16, 17]
    hours[4] = [5, 6, 7, 8, 13, 14, 15, 16, 17]
    hours[5] = [5, 6, 7, 8, 13, 14, 15, 16, 17]
    hours[6] = [5, 6, 7, 8, 9, 10, 11, 13, 14, 15, 16, 17]
    hours[7] = [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]
    hours[8] = [5, 6, 7, 8, 9, 10, 14, 15, 16, 17]
    hours[9] = [5, 6, 7, 8, 13, 14, 15, 16, 17]
    hours[10] = [5, 6, 7, 8, 12, 13, 14, 15, 16, 17]
    hours[11] = [5, 6, 7, 8, 11, 12, 13, 14, 15, 16, 17]
    hours[12] = [5, 6, 7, 8, 11, 12, 13, 14, 15, 16, 17]
    
    df_cat = pd.DataFrame(columns=df.columns, index=df.index)
    i = 0
    for values in df.values:
        cat_arr = []
        for value in values:
            if int(value) in hours[df.index[i].month]:
                cat_arr.append(int(value))
        if len(cat_arr) > 0:
            df_cat['V1'].loc[df.index[i]] = cat_arr[0]
        if len(cat_arr) > 1:
            df_cat['V2'].loc[df.index[i]] = cat_arr[1]
        if len(cat_arr) > 2:
            df_cat['V3'].loc[df.index[i]] = cat_arr[2]
        if len(cat_arr) > 3:
            df_cat['V4'].loc[df.index[i]] = cat_arr[3]
        if len(cat_arr) > 4:
            df_cat['V5'].loc[df.index[i]] = cat_arr[4]
        if len(cat_arr) > 5:
            df_cat['V6'].loc[df.index[i]] = cat_arr[5]
        i += 1  
    
    return df_cat

def cz0(df):
    hours = {}
    hours[1] = [3, 4, 5, 6, 12, 13, 14, 15]
    hours[2] = [3, 4, 5, 13, 14, 15, 16]
    hours[3] = [2, 3, 4, 14, 15, 16]
    hours[4] = [3, 4, 5, 14, 15, 16]
    hours[5] = [3, 4, 5, 6, 14, 15, 16]
    hours[6] = [3, 4, 5, 6, 7, 15, 16]
    hours[7] = [3, 4, 5, 6, 7, 8, 13, 14, 15, 16]
    hours[8] = [4, 5, 6, 7, 12, 13, 14, 15, 16]
    hours[9] = [4, 5, 14, 15, 16]
    hours[10] = [3, 4, 5, 6, 13, 14, 15, 16]
    hours[11] = [3, 4, 5, 6, 13, 14, 15]
    hours[12] = [2, 3, 4, 5, 12, 13, 14, 15]
    
    for j in range(1, 13):
        hours[j] = list(map(lambda x : x + 7, hours[j]))
    
    df_cat = pd.DataFrame(columns=df.columns, index=df.index)
    i = 0
    for values in df.values:
        cat_arr = []
        for value in values:
            if int(value) in hours[df.index[i].month]:
                cat_arr.append(int(value))
        if len(cat_arr) > 0:
            df_cat['V1'].loc[df.index[i]] = cat_arr[0]
        if len(cat_arr) > 1:
            df_cat['V2'].loc[df.index[i]] = cat_arr[1]
        if len(cat_arr) > 2:
            df_cat['V3'].loc[df.index[i]] = cat_arr[2]
        if len(cat_arr) > 3:
            df_cat['V4'].loc[df.index[i]] = cat_arr[3]
        if len(cat_arr) > 4:
            df_cat['V5'].loc[df.index[i]] = cat_arr[4]
        if len(cat_arr) > 5:
            df_cat['V6'].loc[df.index[i]] = cat_arr[5]
        i += 1  
    
    return df_cat

In [4]:
porog=0.0

print ("Number of arguments:", len(sys.argv), "arguments")
print ("Argument List:", str(sys.argv))

try:
    ttt = int(sys.argv[1:][0])
except:
    ttt = 17

try:
    status  = str(sys.argv[2:][0])
except:
    status = ''
    
print('args', ttt, '|', status)


if ttt==0: teritors=['Ленинградская область','Республика Карелия','Волгоградская область','Новгородская область',1,0.2] #88
if ttt==1: teritors=['Волгоградская область','Республика Калмыкия','Астраханская область','Саратовская область',1,0.7]#56
if ttt==2: teritors=['Мурманская область','Республика Карелия','Ленинградская область','Волгоградская область',1,0.63]#0.639
if ttt==3: teritors=['Тульская область','Московская область','Рязанская область','Липецкая область',1,0.85]
if ttt==4: teritors=['Ставропольский край','Краснодарский край','Ростовская область','Республика Калмыкия',1,0.82]#0.875776
if ttt==5: teritors=['Пермский край','Свердловская область','Удмуртская Республика','Кировская область',1,0.5]#0.627329
if ttt==6: teritors=['Краснодарский край','Ростовская область','Ставропольский край','Карачаево-Черкесская Республика',1,0.6]#0.91
if ttt==7: teritors=['Свердловская область','Тюменская область','Курганская область','Челябинская область',1,0.77]#80


if ttt==8: teritors=['Кемеровская область','Новосибирская область','Красноярский край','Республика Хакасия',2,0.79]
if ttt==9: teritors=['Алтайский край','Кемеровская область','Новосибирская область','Республика Хакасия',2,0.98]
if ttt==10: teritors=['Красноярский край','Республика Хакасия','Кемеровская область','Иркутская область',2,0.80]
if ttt==11: teritors=['Республика Хакасия','Красноярский край','Иркутская область','Новосибирская область',2,0.67]
if ttt==12: teritors=['Новосибирская область','Красноярский край','Кемеровская область','Алтайский край',2,1]
if ttt==13: teritors=['Забайкальский край','Иркутская область','Красноярский край','Республика Бурятия',2,0.5]
if ttt==14: teritors=['Республика Тыва','Республика Хакасия','Красноярский край','Иркутская область',2,0.7]    


if ttt==15: teritors=['Республика Бурятия','Забайкальский край','Иркутская область','Красноярский край',2,0]
if ttt==16: teritors=['Хабаровский край','Хабаровский край','Хабаровский край','Хабаровский край',0,0]
if ttt==17: teritors=['Приморский край','Приморский край','Приморский край','Приморский край',0,0]

    
print('-------------',teritors,'-------------')

Number of arguments: 3 arguments
Argument List: ['/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py', '-f', '/root/.local/share/jupyter/runtime/kernel-ae3aee9d-e4c9-4b56-83e0-f5e7449d28ef.json']
args 17 | /root/.local/share/jupyter/runtime/kernel-ae3aee9d-e4c9-4b56-83e0-f5e7449d28ef.json
------------- ['Приморский край', 'Приморский край', 'Приморский край', 'Приморский край', 0, 0] -------------

In [5]:
if teritors[4] == 1:
    cz_f = cz1
    
if teritors[4] == 2:
    cz_f = cz2

if teritors[4] == 0:
    cz_f = cz0

In [6]:
ter = teritors[0]

In [7]:
ter

'Приморский край'

In [8]:
CAT=pd.read_excel('./models/'+ter+'.xlsx',header=0,index_col=0)
print('Кстбуст статистика')
print(CAT.loc[dataT][:5])

Кстбуст статистика
V1    21
V2    20
V3    11
V4    22
V5    10
Name: 2021-09-21 00:00:00, dtype: int64

In [9]:
cz_f(CAT).loc[dataT][:5]

V1     21
V2     11
V3     22
V4    NaN
V5    NaN
Name: 2021-09-21 00:00:00, dtype: object

In [10]:
# на текущий день
d_now = list(cz_f(CAT).loc[dataT][:3].values)
d_now

[21, 11, 22]

In [11]:
prognoz = cz_f(CAT)[CAT.index>=dataT][['V1','V2','V3']][:60]
prognoz

            V1  V2  V3
2021-09-21  21  11  22
2021-09-22  21  22  11
2021-09-23  21  22  11
2021-09-24  21  11  22
2021-09-27  21  22  11
2021-09-28  21  22  11
2021-09-29  21  22  11
2021-09-30  21  11  22
2021-10-01  20  21  11
2021-10-04  21  20  10
2021-10-05  20  21  10
2021-10-06  20  21  11
2021-10-07  20  21  10
2021-10-08  20  21  10
2021-10-11  20  21  10
2021-10-12  20  21  10
2021-10-13  20  21  10
2021-10-14  20  21  10
2021-10-15  20  21  11
2021-10-18  20  21  11
2021-10-19  20  21  10
2021-10-20  20  21  11
2021-10-21  20  21  11
2021-10-22  20  10  11
2021-10-25  20  21  10
2021-10-26  20  21  10
2021-10-27  20  21  10
2021-10-28  20  21  10
2021-10-29  20  11  10
2021-11-01  20  21  10
2021-11-02  20  21  11
2021-11-03  20  21  11
2021-11-04  20  10  21
2021-11-05  20  11  10
2021-11-08  20  21  11
2021-11-09  20  21  10
2021-11-10  20  21  10
2021-11-11  20  10  21
2021-11-12  20  10  11
2021-11-15  20  21  10
2021-11-16  20  10  21
2021-11-17  20  10  21
2021-11-18  20  10  11
2021-11-19  20  11  10
2021-11-22  20  10  21
2021-11-23  20  10  11
2021-11-24  20  10  11
2021-11-25  20  10  11
2021-11-26  20  10  11
2021-11-29  20  10  11
2021-11-30  20  10  21
2021-12-01  19  20  11
2021-12-02  19  20  11
2021-12-03  19  11  20
2021-12-06  19  20  11
2021-12-07  19  20  11
2021-12-08  19  20  11
2021-12-09  19  20  11
2021-12-10  20  19  10
2021-12-13  19  20  11

In [269]:
for i in prognoz.index[:45]:
#     prognoz['V3'].loc[i] = ""
    if pd.isna(prognoz['V1'].loc[i]):
        prognoz['V1'].loc[i] = 'NULL'
    if pd.isna(prognoz['V2'].loc[i]):
        prognoz['V2'].loc[i] = 'NULL'
    if pd.isna(prognoz['V3'].loc[i]):
        prognoz['V3'].loc[i] = 'NULL'
    print(i,prognoz['V1'].loc[i],prognoz['V2'].loc[i],prognoz['V3'].loc[i])

2021-09-07 00:00:00 21 22 11
2021-09-08 00:00:00 21 22 11
2021-09-09 00:00:00 21 22 11
2021-09-10 00:00:00 21 11 22
2021-09-13 00:00:00 21 22 11
2021-09-14 00:00:00 21 22 11
2021-09-15 00:00:00 21 22 11
2021-09-16 00:00:00 21 22 11
2021-09-17 00:00:00 21 11 22
2021-09-20 00:00:00 21 11 22
2021-09-21 00:00:00 21 11 22
2021-09-22 00:00:00 21 22 11
2021-09-23 00:00:00 21 22 11
2021-09-24 00:00:00 21 11 22
2021-09-27 00:00:00 21 22 11
2021-09-28 00:00:00 21 22 11
2021-09-29 00:00:00 21 22 11
2021-09-30 00:00:00 21 11 22
2021-10-01 00:00:00 20 21 11
2021-10-04 00:00:00 21 20 10
2021-10-05 00:00:00 20 21 10
2021-10-06 00:00:00 20 21 11
2021-10-07 00:00:00 20 21 10
2021-10-08 00:00:00 20 21 10
2021-10-11 00:00:00 20 21 10
2021-10-12 00:00:00 20 21 10
2021-10-13 00:00:00 20 21 10
2021-10-14 00:00:00 20 21 10
2021-10-15 00:00:00 20 21 11
2021-10-18 00:00:00 20 21 11
2021-10-19 00:00:00 20 21 10
2021-10-20 00:00:00 20 21 11
2021-10-21 00:00:00 20 21 11
2021-10-22 00:00:00 20 10 11
2021-10-25 00:00:00 20 21 10
2021-10-26 00:00:00 20 21 10
2021-10-27 00:00:00 20 21 10
2021-10-28 00:00:00 20 21 10
2021-10-29 00:00:00 20 11 10
2021-11-01 00:00:00 20 21 10
2021-11-02 00:00:00 20 21 11
2021-11-03 00:00:00 20 21 11
2021-11-04 00:00:00 20 10 21
2021-11-05 00:00:00 20 11 10
2021-11-08 00:00:00 20 21 11

In [270]:
import cx_Oracle
#con_str=cx_Oracle.makedsn("10.72.31.10","1521","snab")
#con = cx_Oracle.connect(user="DMITRIEVMM",password="DMITRIEVMM",dsn=con_str, encoding="UTF-8")
#cursor=con.cursor()

for i in prognoz.index[:45]:
    if pd.isna(prognoz['V1'].loc[i]):
        prognoz['V1'].loc[i] = 'NULL'
    if pd.isna(prognoz['V2'].loc[i]):
        prognoz['V2'].loc[i] = 'NULL'
    if pd.isna(prognoz['V3'].loc[i]):
        prognoz['V3'].loc[i] = 'NULL'
    print(i,prognoz['V1'].loc[i],prognoz['V2'].loc[i],prognoz['V3'].loc[i])
#    cur = con.cursor()
    '''if str(i)[:10]=='2021-02-22':
        i='2021-02-20'''
    #query = "DELETE FROM ATSLOAD.GES_OTHER_FORECASTS WHERE FC_DAY = '"+str(i).replace('-','').replace(' 00:00:00','')+"' AND REGION = '"+ter+"'"
    #rez=cur.execute(str(query))    
    
    query = "INSERT INTO ATSLOAD.GES_OTHER_FORECASTS (FC_DAY , REGION , HOUR1, HOUR2, HOUR3   ) VALUES ('"+str(i).replace('-','').replace(' 00:00:00','')+"', '"+ter+"', "+str(prognoz['V1'].loc[i])+","+str(prognoz['V2'].loc[i])+","+str(prognoz['V3'].loc[i])+" ) "
    print(query)
#    rez=cur.execute(str(query))
    
#    rez=cur.execute(str("COMMIT "))

In [271]:

import pyodbc 
server = r'10.79.226.101'
database = r'TradeInfo' 
username = r'sibgenco.local\omima'
password = r'VxjNOJV]!3' 
conn = pyodbc.connect('DRIVER={FreeTDS};SERVER='+server+';PORT=1433;DATABASE='+database+';UID='+username+';PWD='+ password+';TDS_VERSION=8.0;')


for i in prognoz.index[:45]:
    if pd.isna(prognoz['V1'].loc[i]):
        prognoz['V1'].loc[i] = 'NULL'
    if pd.isna(prognoz['V2'].loc[i]):
        prognoz['V2'].loc[i] = 'NULL'
    if pd.isna(prognoz['V3'].loc[i]):
        prognoz['V3'].loc[i] = 'NULL'
    print(i,prognoz['V1'].loc[i],prognoz['V2'].loc[i],prognoz['V3'].loc[i])
    '''if str(i)[:10]=='2021-02-22':
        i='2021-02-20'''     

    
    #query = "DELETE FROM ATSLOAD.GES_OTHER_FORECASTS WHERE FC_DAY = '"+str(i).replace('-','').replace(' 00:00:00','')+"' AND REGION = '"+ter+"'"

    
    cursor = conn.cursor()
    query = "INSERT SrcSCH (FC_DAY , REGION , HOUR1, HOUR2, HOUR3,ModelName   ) VALUES ('"+str(i).replace('-','').replace(' 00:00:00','')+"', '"+ter+"', "+str(prognoz['V1'].loc[i])+","+str(prognoz['V2'].loc[i])+","+str(prognoz['V3'].loc[i])+",'v1' ) "
    print(query)
    cursor.execute(query)
    

conn.commit()

In [272]:
'''import pyodbc 
server = r'10.79.226.101'
database = r'TradeInfo' 
username = r'sibgenco.local\omima'
password = r'VxjNOJV]!3' 
conn = pyodbc.connect('DRIVER={FreeTDS};SERVER='+server+';PORT=1433;DATABASE='+database+';UID='+username+';PWD='+ password+';TDS_VERSION=8.0;')

stmt = "select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = N'SrcSCH' ;"
df = pd.read_sql(stmt,conn)'''

'import pyodbc \nserver = r\'10.79.226.101\'\ndatabase = r\'TradeInfo\' \nusername = r\'sibgenco.local\\omima\'\npassword = r\'VxjNOJV]!3\' \nconn = pyodbc.connect(\'DRIVER={FreeTDS};SERVER=\'+server+\';PORT=1433;DATABASE=\'+database+\';UID=\'+username+\';PWD=\'+ password+\';TDS_VERSION=8.0;\')\n\nstmt = "select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = N\'SrcSCH\' ;"\ndf = pd.read_sql(stmt,conn)'

In [273]:
import pandas
from openpyxl import load_workbook
from openpyxl.styles import Font, Fill

book = load_workbook(str(pathP+'/rez_'+str(teritors[4])+'cz.xlsx'))
writer = pandas.ExcelWriter(pathP+'/rez_'+str(teritors[4])+'cz.xlsx', engine='openpyxl')
writer.book = book
writer.sheets = dict((ws.title, ws) for ws in book.worksheets)
prognoz[['V1','V2','V3']].to_excel(writer, ter)

sheet2 = book.get_sheet_by_name(ter)
sheet2['A1'] = ter
sheet2['A1'].font = Font(bold = True)

sheet2['B2'].font = Font(color = "FF0000",bold = True,size=14)
sheet2['C2'].font = Font(color = "FF0000",bold = True,size=14)
sheet2['D2'].font = Font(color = "FF0000",bold = True,size=14)
for i in range(3,7):
    sheet2['B'+str(i)].font = Font(color = "008000",bold = True,size=14)
    sheet2['C'+str(i)].font = Font(color = "008000",bold = True,size=14)
    sheet2['D'+str(i)].font = Font(color = "008000",bold = True,size=14)

sheet2.column_dimensions["A"].width = 25.0


#sheet2['B2'].font = Font(size=16)

writer.save()

In [274]:
# prognoz

In [275]:
'''
df_excel = pd.read_excel(pathP+'/log/log2.xlsx',sheet_name=ter)
book = load_workbook(pathP+'/log/log2.xlsx')
writer_log = pd.ExcelWriter(pathP+'/log/log2.xlsx', engine='openpyxl')
writer_log.book = book
writer_log.sheets = dict((ws.title, ws) for ws in book.worksheets)

prognoz[['V1','V2','V3']][:1].to_excel(writer_log, ter, startrow=len(df_excel)+1,header=False)

prognoz[['V1','V2','V3']][1:2].to_excel(writer_log, ter, startrow=len(df_excel)+1,startcol=4,header=False,index=False)
prognoz[['V1','V2','V3']][2:3].to_excel(writer_log, ter, startrow=len(df_excel)+1,startcol=7,header=False,index=False)
prognoz[['V1','V2','V3']][3:4].to_excel(writer_log, ter, startrow=len(df_excel)+1,startcol=10,header=False,index=False)
prognoz[['V1','V2','V3']][4:5].to_excel(writer_log, ter, startrow=len(df_excel)+1,startcol=13,header=False,index=False)


sheet2 = book.get_sheet_by_name(ter)
sheet2['B'+str(len(df_excel)+2)].font = Font(bold = True,size=14)
sheet2['C'+str(len(df_excel)+2)].font = Font(bold = True,size=14)
sheet2['D'+str(len(df_excel)+2)].font = Font(bold = True,size=14)

sheet2.column_dimensions["A"].width = 25.0

sheet2['Q'+str(len(df_excel)+2)]=str(datetime.datetime.now())


writer_log.save()
'''

'\ndf_excel = pd.read_excel(pathP+\'/log/log2.xlsx\',sheet_name=ter)\nbook = load_workbook(pathP+\'/log/log2.xlsx\')\nwriter_log = pd.ExcelWriter(pathP+\'/log/log2.xlsx\', engine=\'openpyxl\')\nwriter_log.book = book\nwriter_log.sheets = dict((ws.title, ws) for ws in book.worksheets)\n\nprognoz[[\'V1\',\'V2\',\'V3\']][:1].to_excel(writer_log, ter, startrow=len(df_excel)+1,header=False)\n\nprognoz[[\'V1\',\'V2\',\'V3\']][1:2].to_excel(writer_log, ter, startrow=len(df_excel)+1,startcol=4,header=False,index=False)\nprognoz[[\'V1\',\'V2\',\'V3\']][2:3].to_excel(writer_log, ter, startrow=len(df_excel)+1,startcol=7,header=False,index=False)\nprognoz[[\'V1\',\'V2\',\'V3\']][3:4].to_excel(writer_log, ter, startrow=len(df_excel)+1,startcol=10,header=False,index=False)\nprognoz[[\'V1\',\'V2\',\'V3\']][4:5].to_excel(writer_log, ter, startrow=len(df_excel)+1,startcol=13,header=False,index=False)\n\n\nsheet2 = book.get_sheet_by_name(ter)\nsheet2[\'B\'+str(len(df_excel)+2)].font = Font(bold = True,size=14)\nsheet2[\'C\'+str(len(df_excel)+2)].font = Font(bold = True,size=14)\nsheet2[\'D\'+str(len(df_excel)+2)].font = Font(bold = True,size=14)\n\nsheet2.column_dimensions["A"].width = 25.0\n\nsheet2[\'Q\'+str(len(df_excel)+2)]=str(datetime.datetime.now())\n\n\nwriter_log.save()\n'

In [12]:
str(datetime.datetime.now())

'2021-09-20 17:43:32.522760'